# action.yml
name: 'docker action'
description: 'build && make && test application'
inputs:
  args: 
    description: 'args'
    required: true
    default: ''
outputs:
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}