name: Build

on: 
  push:
    branches: 
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake ..
    - name: make
      run: make -j
