name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run docker container to build
      using: 'docker'
      image: 'Dockerfile'
          args: cmake .. && make -j
          
