name: C/C++ CI

on: 
  push:
    branches: 
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: mkdir build & cd build & cmake ..
    - name: make
      run: make -j
  test:
    runs-on:  ubuntu-latest
    steps:
      - name: test
        run: build/bin/net-test
        timeout-minutes: 5
