name: Lint

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.yml'
jobs:
  lint:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.5
        with:
          source: './'
          exclude: './build,./include/net/third,./lib/net/third,./.github,./doc'
          extensions: 'hpp,cc,h,c,cpp'
          clangFormatVersion: 9
