name: Lint

on:
  push:
      
jobs:
  lint:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.5
        with:
          source: './'
          exclude: './build'
          extensions: 'hpp,cc,h,c,cpp'
          clangFormatVersion: 9
