name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.yml'
jobs:
  test:
    runs-on:  ubuntu-latest
    container: archlinux:latest
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: | 
        pacman -Sy --noconfirm
        pacman -S --noconfirm make cmake gcc ffmpeg qt5-base google-glog gtest boost git gflags crypto++
    - name: build
      run: |
        mkdir build
        cd build
        cmake .. 
        make -j
    - name: test
      run: |
        cd build/bin
        ./test-net
          
