name: Test

on:
  push:

jobs:
  test:
    runs-on:  ubuntu-latest
    needs: Build
    steps:
      - name: run docker container to test
        using: 'docker'
        image: 'Dockerfile'
          args: cmake .. && make -j && test-net
