name: Test

on:   
  push:
    branches: 
      - master
      - release/*

jobs:
  test:
    runs-on:  ubuntu-latest
    needs: build
    steps:
      - name: test
        run: build/bin/net-test
        timeout-minutes: 5
